// Generated by CoffeeScript 1.9.1
(function() {
  var grab;

  this.DOMGrab = (function() {
    function DOMGrab() {}

    return DOMGrab;

  })();

  grab = this.DOMGrab.grab = function(selector) {
    var k, ret, v;
    switch (typeof selector) {
      case 'string':
        return document.querySelector(selector);
      case 'object':
        if (selector instanceof Object) {
          ret = {};
          for (k in selector) {
            v = selector[k];
            if (selector.hasOwnProperty(k)) {
              ret[k] = grab(v);
            }
          }
          return ret;
        } else {
          return selector;
        }
        break;
      case 'function':
        return grab(selector());
      case 'undefined':
      case 'boolean':
      case 'number':
        return selector;
      default:
        throw "selector type (" + selector + ") is not support";
    }
  };

}).call(this);

//# sourceMappingURL=DOMGrab.js.map
